const Path = {
    HOME: "/",
    METAL_CONVERTER: "/jewellery/metal-converter",
    RING_WEIGHT: "/jewellery/ring-weight",
    RING_RESIZER: "/jewellery/ring-resizer",
    ROLLING_WIRE: "/jewellery/rolling-wire",
    CALCULATIONS: '/jewellery/calculations',
    REGISTER: "/core/register",
    LOGIN: "/core/login",
    FORGOT_PASSWORD: "/core/forgot-password",
    CONFIRMATION_SCREEN: "/core/confirmation-screen",
    RESET_PASSWORD: "/core/reset-password",
    FIRST_TIME_SETUP: "/admin/first-time-setup",
    USER_SETTINGS: '/my-account/user-settings',
    UPDATE_PASSWORD: '/my-account/update-password',
    METAL_SETTINGS: '/my-account/metal-settings',
    RING_SIZE_SETTINGS: '/my-account/ring-size-settings',
    USER_ACCOUNTS: '/admin/user-accounts',
    DEFAULT_METALS: '/admin/default-metals',
    DEFAULT_RING_SIZES: '/admin/default-ring-sizes',
    CONFIGURE_EMAIL: '/admin/configure-email',
    ERROR_LEDGER: '/admin/error-ledger',
}

export default Path
